kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etherpad-plugins
  namespace: etherpad
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etherpad-mysql
  namespace: etherpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
