apiVersion: v1
kind: Service
metadata:
  name: heketi
spec:
  selector:
    app: heketi
  ports:
  - name: heketi
    port: 8080
    targetPort: 8080

---
kind: Endpoints
apiVersion: v1
metadata:-
  name: "heketi-storage-endpoints"
  namespace: heketi
subsets:
- addresses:
  - ip: "10.20.30.1"
  ports:
  - port: 1
- addresses:
  - ip: "10.20.30.2"
  ports:
  - port: 1
- addresses:
  - ip: "10.20.30.3"
  ports:
  - port: 1

---
kind: Service
apiVersion: v1
metadata:-
  name: "heketi-storage-endpoints"
  namespace: heketi
spec:
 ports:
 - port: 1
   targetPort: 0
