- name: Remove apticron
  apt:
    name: apticron
    state: absent

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades

- name: Enable unattended-upgrades
  copy:
    src: "20auto-upgrades"
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    mode: 0644
    owner: root
    group: root

- name: Configure unattended-upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    mode: 0644
    owner: root
    group: root
