---
- block:
  - name: "Debian Install stable ppa for Glusterfs"
    apt_repository:
      repo: "{{ glusterfs_repo_debian }}"
      state: present

  - name: "Debian Install glusterfs"
    package:
      name: glusterfs-server
      state: present
      update_cache: true
    notify:
      - rpcbind-started
      - glusterfs-started

  when: ansible_os_family == 'Debian'


- name: "Centos : Install GlusterFS"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ glusterfs_repo_centos }}"
  notify:
    - glusterd-started
  when: ansible_os_family == 'RedHat'
