######################
######## main ########
######################

main_os_net_config_file: conf/network_config.yaml
main_libvirt_network_name: internal
main_libvirt_bridge_name: br-int
main_private_network: 10.20.30.0/24
main_dhcp_interface: br-int
main_dhcp_listen_ip: 10.20.30.1
main_dhcp_default_gw: 10.20.30.1
main_dhcp_range:
  start: 10.20.30.20
  end: 10.20.30.30
main_libvirt_hosts:
  - name: fydrah-c1
    image: Fedora-Atomic-28
    size: 20G
    mac: "52:54:10:20:30:21"
    ip: 10.20.30.21/24
    cpu: 2
    ram: 8192
    dns: 9.9.9.9
    disks:
      - name: docker
        size: 40G
        dev_target: vdb
  - name: fydrah-c2
    image: Fedora-Atomic-28
    size: 20G
    mac: "52:54:10:20:30:22"
    ip: 10.20.30.22/24
    cpu: 2
    ram: 8192
    dns: 9.9.9.9
    disks:
      - name: docker
        size: 40G
        dev_target: vdb
  - name: fydrah-c3
    image: Fedora-Atomic-28
    size: 20G
    mac: "52:54:10:20:30:23"
    ip: 10.20.30.23/24
    cpu: 2
    ram: 8192
    dns: 9.9.9.9
    disks:
      - name: docker
        size: 40G
        dev_target: vdb
