---
# tasks file for keepalived

- name: Install keepalived
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - keepalived
    - python-pip
  when: ansible_os_family == 'Debian'

- name: Install keepalived
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - keepalived
    - python2-pip
  when: ansible_os_family == 'RedHat'

- name: Install slumber
  pip:
    name: slumber
    state: present

- name: Add online script
  template:
    src: online-switch.j2
    dest: /usr/local/bin/online-switch
    mode: 0700
    owner: root
    group: root
  notify: keepalived-restarted

- name: Push heketi state script
  copy:
    src: heketi_keepalived.sh
    dest: /usr/local/bin/
    mode: 0700
    owner: root
    group: root

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0600
    owner: root
    group: root
  notify: keepalived-restarted
