network_config:
  - type: ovs_bridge
    name: br-ex
    use_dhcp: false
    addresses:
      - ip_netmask: 195.154.156.211/24
    routes:
      - ip_netmask: 0.0.0.0/0
        next_hop: 195.154.156.1
        default: true
    members:
      - type: interface
        name: eth0
  - type: ovs_bridge
    name: br-int
    use_dhcp: false
    addresses:
      - ip_netmask: 10.20.30.1/24
    members: []
  - type: ovs_patch_port
    name: br-ex-patch
    bridge_name: br-int
    peer: br-int-patch
  - type: ovs_patch_port
    name: br-int-patch
    bridge_name: br-ex
    peer: br-ex-patch
