---
apiVersion: v1
kind: Namespace
metadata:
  name: monero

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: minerd
  labels:
    name: minerd
    app: monero
  namespace: monero
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: minerd
    spec:
      containers:
      - image: fhardy/minerd
        name: minerd
        env:
          - name: WALLET_ADDRESS
            value: "4ARNszZkRZphCgQLTDmEn8CJeEtKWk3hqemm7VwrrfTA8wvUfxqY1UagkZ6X1eYQZb4PdwBCqEvLMZgJdNwaYDgM7GGAjub"
          - name: POOL
            value: "stratum+tcp://pool.supportxmr.com:3333"
          - name: NTHREAD
            value: "3"
          - name: PASS
            value: "flav.hardy@gmail.com"
