#!/usr/bin/env ansible-playbook

- hosts: ldap
  tasks:
    - include_vars: conf/plain-vars.yml
    - include_vars: conf/encrypt-vars.yml
  tags:
    - always

- hosts: ldap
  become: true
  roles:
    - ldap
